title: Craveytrain
subtitle: I'm a little geek bot, short and stout…
author: Mike Cravey
description: The blog of Mike Cravey (@craveytrain).
rss: /atom.xml
stylesheet: /css/default.css
script: /js/main.min.js
domain: craveytrain.com
keywords:
    - engineering
    - development
    - user interface
